const container = document.createElement('div');
container.style.position = 'fixed';
container.style.bottom = '40px';
container.style.right = '10px';
container.style.zIndex = '1000';
container.style.textAlign = 'center';
const title = document.createElement('div');
title.innerText = 'Scientific Research Assistant';
title.style.backgroundColor = '#333379';
title.style.color = '#FFFFFF';
title.style.padding = '5px 10px';
title.style.borderRadius = '5px 5px 0 0';
title.style.fontSize = '17px';
title.style.marginBottom = '0px';
const textButton = document.createElement('button');
textButton.innerText = 'If you cannot find this paper or book on sci-hub, click here to request it from us.';
textButton.style.backgroundColor = '#333379';
textButton.style.color = '#FFFFFF';
textButton.style.padding = '10px 20px';
textButton.style.border = 'none';
textButton.style.borderRadius = '0 0 5px 5px';
textButton.style.cursor = 'pointer';
textButton.style.width = '300px';
textButton.style.whiteSpace = 'normal';
textButton.style.fontSize = '14px';
textButton.style.textAlign = 'center';
textButton.style.zIndex = '1000';
container.appendChild(title);
container.appendChild(textButton);
document.body.appendChild(container);
textButton.addEventListener('click', () => {
        chrome.runtime.sendMessage({ action: 'openNewTab' });
    });
